import { TYPES, RARITIES, DIFFICULTIES, BACKGROUNDS } from './systems.js';

const DEFAULT={used:0,day:'',weapons:[],blueprints:[],backgrounds:[],explore:null,rank:'F'};
let state=loadState(), selectedType=0, blueprintType=0, forgeContext=null, step=0, quality=50, selectedDifficulty=0;

const $=id=>document.getElementById(id);
function loadState(){try{return Object.assign({},DEFAULT,JSON.parse(localStorage.getItem('blacksmith_repo_v051')||'{}'))}catch(e){return {...DEFAULT}}}
function saveState(){localStorage.setItem('blacksmith_repo_v051',JSON.stringify(state));renderAll()}
function dayKey(){const d=new Date();if(d.getHours()<5)d.setDate(d.getDate()-1);return d.toISOString().slice(0,10)}
function resetDaily(){const key=dayKey();if(state.day!==key){state.day=key;state.used=0;saveState()}}
function maxForges(){return 3+(['SS','SSS','BLACK Smith'].includes(state.rank)?1:0)+(state.rank==='BLACK Smith'?1:0)}
function remaining(){return Math.max(0,maxForges()-state.used)}
function showToast(text){const el=$('toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1700)}
function go(page){resetDaily();document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(page).classList.add('active');document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===page));renderAll();scrollTo(0,0)}
function enter(){$('nav').style.display='grid';go('home')}
function randomInt(a,b){return Math.floor(Math.random()*(b-a+1))+a}
function rollRarity(){let n=Math.random()*100,total=0;for(const rarity of RARITIES){total+=rarity.probability;if(n<total)return rarity}return RARITIES.at(-1)}
function rollBackground(){let n=Math.random()*100,total=0;for(const bg of BACKGROUNDS){total+=bg.probability;if(n<total)return bg.name}return null}
function rollSkill(type){const n=Math.random()*100;if(n>=5)return {tier:'ノースキル'};const atk=n<.5?randomInt(100,150):n<1?randomInt(80,150):randomInt(10,150),agi=n<.5?randomInt(20,50):0;let active=null;if(n<.5&&Math.random()<.5){const pool=['ソウルインジェクション','神殺し'];const map={'ナックル':'ヴェノムスプラッシュ','ハンマー':'グラビティプレス','斧':'グラビティプレス','大剣':'レイジングスラッシュ','双剣':'シャドウスタブ','ダガー':'シャドウスタブ','槍':'スパイラルランス'};if(map[type])pool.push(map[type]);active=pool[randomInt(0,pool.length-1)]}return {tier:n<.01?'神域':n<.5?'超希少':n<1?'希少':'付与',atk,agi,active}}
function createWeapon(type,source){const rarity=rollRarity(),curse=['F','E','D','C','B'].includes(state.rank)&&Math.random()<.05,transcended=Math.random()<.01;let name=['黒鉄','灼熱','蒼雷','月影','星喰','歪曲'][randomInt(0,5)]+'の'+type.name;if(curse)name='呪われた'+name;if(transcended)name='超越した'+name;const background=rollBackground();if(background&&!state.backgrounds.includes(background))state.backgrounds.push(background);const penalty=curse?.8:1,boost=transcended?1.1:1;return {id:String(Date.now()+Math.random()),name,type:type.name,icon:type.icon,rarity:rarity.name,color:rarity.color,attack:Math.round(randomInt(80,150)*rarity.multiplier*penalty*boost),agility:Math.round(randomInt(20,60)*penalty*boost),skill:rollSkill(type.name),background,source,code:'BS-'+Math.random().toString(36).slice(2,6).toUpperCase()+'-'+Math.random().toString(36).slice(2,8).toUpperCase()}}
function renderTypes(){$('typeGrid').innerHTML=TYPES.map((t,i)=>`<button class="choice ${i===selectedType?'active':''}" data-type="${i}" data-mode="forge">${t.icon}<br><small>${t.name}</small></button>`).join('');$('bpTypeGrid').innerHTML=TYPES.map((t,i)=>`<button class="choice ${i===blueprintType?'active':''}" data-type="${i}" data-mode="blueprint">${t.icon}<br><small>${t.name}</small></button>`).join('');$('typeLabel').textContent=TYPES[selectedType].name;$('bpTypeLabel').textContent=TYPES[blueprintType].name}
function updatePreview(){$('lengthLabel').textContent=$('lengthRange').value;$('weirdLabel').textContent=$('weirdRange').value;$('forgePreview').textContent=TYPES[selectedType].icon;$('forgePreview').style.transform=`rotate(${(+$('weirdRange').value-50)/5}deg) scale(${.75+(+$('lengthRange').value/170)})`;$('bpPreview').textContent=TYPES[blueprintType].icon}
function saveBlueprint(){state.blueprints.unshift({name:$('bpName').value||'無銘の設計図',type:blueprintType});saveState();showToast('設計図を保存しました')}
function startForge(source){if(remaining()<=0)return showToast('本日の鍛造回数を使い切りました');if(state.weapons.length>=14)return showToast('保管庫が満杯です');forgeContext={source,type:source==='設計図鍛造'?blueprintType:selectedType};step=0;quality=50;go('process')}
const STEP_NAMES=['加熱','鍛打','成形','焼入れ','仕上げ','完成'];
function renderProcess(){$('steps').innerHTML=STEP_NAMES.map((s,i)=>`<div class="step ${i===step?'active':''}">${s}</div>`).join('');$('processText').textContent=['素材を赤熱させます','芯を鍛えます','輪郭を整えます','硬度を定着させます','刃と刻印を仕上げます','最後の一打を入れます'][step];$('processBtn').textContent=step===5?'完成させる':STEP_NAMES[step]+'する';$('processIcon').textContent=step<1?'🔥':step<4?TYPES[forgeContext.type].icon:'✨';$('quality').textContent=quality}
function advanceForge(){quality=Math.min(100,quality+randomInt(4,11));if(step<5){step++;renderProcess()}else{const weapon=createWeapon(TYPES[forgeContext.type],forgeContext.source);weapon.quality=quality;state.weapons.unshift(weapon);state.used++;saveState();showWeapon(weapon)}}
function showWeapon(w){$('sheet').innerHTML=`<h3 style="text-align:center">鍛造完了</h3><div class="preview"><div class="bigWeapon">${w.icon}</div></div><div style="text-align:center"><span class="badge" style="color:${w.color}">${w.rarity}</span><h2>${w.name}</h2>${w.background?`<p style="color:#d9a8ff">特殊背景：${w.background}</p>`:''}</div><div class="row"><span>攻撃力</span><b>${w.attack}</b></div><div class="row"><span>俊敏</span><b>${w.agility}</b></div><div class="row"><span>スキル</span><b>${w.skill.tier}</b></div>${w.skill.atk?`<div class="row"><span>攻撃補正</span><b>+${w.skill.atk}%</b></div>`:''}${w.skill.agi?`<div class="row"><span>俊敏補正</span><b>+${w.skill.agi}%</b></div>`:''}${w.skill.active?`<div class="row"><span>アクティブ</span><b>${w.skill.active}</b></div>`:''}<button class="primary mt12" data-close-modal>保管庫へ</button>`;$('modal').classList.add('show')}
function renderInventory(){$('invCount').textContent=state.weapons.length;$('inventoryGrid').innerHTML=state.weapons.map((w,i)=>`<button class="weaponCard" data-weapon-index="${i}"><span class="badge" style="color:${w.color}">${w.rarity}</span><div class="icon">${w.icon}</div><b>${w.name}</b><small class="muted">${w.type}</small></button>`).join('')||'<div class="muted">まだ武器がありません</div>'}
function renderExplore(){$('exploreOptions').innerHTML=DIFFICULTIES.map((d,i)=>`<div class="explore ${i===selectedDifficulty?'active':''}" data-diff="${i}"><b>${d.name}</b><span style="float:right">${Math.round(d.durationMs/60000*10)/10}分</span></div>`).join('');if(state.explore){$('exploreOptions').style.display='none';$('exploreBtn').style.display='none';$('running').classList.remove('hidden');const now=Date.now(),done=now>=state.explore.end,left=Math.max(0,state.explore.end-now),total=state.explore.end-state.explore.start;$('runningLabel').textContent=done?'探索から帰還しました':`残り ${Math.ceil(left/1000)}秒`;$('progress').style.width=(done?100:(1-left/total)*100)+'%';$('exploreStatus').textContent=done?'帰還済み':'探索中'}else{$('exploreOptions').style.display='block';$('exploreBtn').style.display='block';$('running').classList.add('hidden');$('exploreStatus').textContent='待機中'}}
function startExplore(){if(state.explore)return;const d=DIFFICULTIES[selectedDifficulty],now=Date.now();state.explore={start:now,end:now+d.durationMs,min:d.rewardMin,max:d.rewardMax};saveState()}
function claimExplore(){if(!state.explore||Date.now()<state.explore.end)return showToast('まだ探索中です');const amount=randomInt(state.explore.min,state.explore.max);state.explore=null;saveState();showToast(`鉱石を${amount}個獲得しました`)}
function renderAll(){resetDailySafe();$('remainTop').textContent=`${remaining()}/${maxForges()}`;$('remainForge').textContent=`${remaining()}/${maxForges()}`;$('heroWeapon').textContent=state.weapons[0]?.icon||'⚔️';$('bpCount').textContent=state.blueprints.length;$('bpList').innerHTML=state.blueprints.map(b=>`<div class="card"><b>${b.name}</b><small class="muted"> ${TYPES[b.type].name}</small></div>`).join('');$('bgCount').textContent=state.backgrounds.length;$('bgGrid').innerHTML=BACKGROUNDS.map(b=>`<div class="weaponCard"><b>${state.backgrounds.includes(b.name)?b.name:'？？？？'}</b></div>`).join('');renderTypes();updatePreview();renderInventory();renderExplore();if($('process').classList.contains('active'))renderProcess()}
function resetDailySafe(){const k=dayKey();if(state.day!==k){state.day=k;state.used=0;localStorage.setItem('blacksmith_repo_v051',JSON.stringify(state))}}

document.addEventListener('click',e=>{const goBtn=e.target.closest('[data-go]');if(goBtn)go(goBtn.dataset.go);const navBtn=e.target.closest('[data-page]');if(navBtn)go(navBtn.dataset.page);const typeBtn=e.target.closest('[data-type]');if(typeBtn){if(typeBtn.dataset.mode==='forge')selectedType=+typeBtn.dataset.type;else blueprintType=+typeBtn.dataset.type;renderTypes();updatePreview()}const diffBtn=e.target.closest('[data-diff]');if(diffBtn){selectedDifficulty=+diffBtn.dataset.diff;renderExplore()}const weaponBtn=e.target.closest('[data-weapon-index]');if(weaponBtn)showWeapon(state.weapons[+weaponBtn.dataset.weaponIndex]);if(e.target.closest('[data-close-modal]')){$('modal').classList.remove('show');go('inventory')}if(e.target===$('modal'))$('modal').classList.remove('show')})
document.querySelector('[data-action="enter"]').onclick=enter;
document.querySelector('[data-action="save-blueprint"]').onclick=saveBlueprint;
document.querySelector('[data-action="start-free-forge"]').onclick=()=>startForge('自由鍛造');
document.querySelector('[data-action="start-blueprint-forge"]').onclick=()=>startForge('設計図鍛造');
document.querySelector('[data-action="advance-forge"]').onclick=advanceForge;
document.querySelector('[data-action="start-explore"]').onclick=startExplore;
document.querySelector('[data-action="claim-explore"]').onclick=claimExplore;
$('lengthRange').oninput=updatePreview;$('weirdRange').oninput=updatePreview;
setInterval(()=>{if($('explore').classList.contains('active'))renderExplore()},1000);
resetDaily();renderAll();
